apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN ics-dhcp
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: ics-dhcp
    location: lan
  name: ics-dhcp
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/ics-dhcp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ics-dhcp
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN ics-dhcp
      creationTimestamp: null
      labels:
        k8s-app: ics-dhcp
        location: lan
      name: ics-dhcp
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: marvinmarvin/docker-k8s-ics-dhcp
        imagePullPolicy: Always
        name: ics-dhcp
        volumeMounts:
        - mountPath: /etc/dhcp
          name: k8s-cfg-ics-dhcp-etc
        - mountPath: /var/lib/dhcp
          name: k8s-cfg-ics-dhcp-var
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: k8s-cfg-ics-dhcp-etc
        hostPath:
          path: /root/k8s-cfg/ics-dhcp/etc
          type: Directory
      - name: k8s-cfg-ics-dhcp-var
        hostPath:
          path: /root/k8s-cfg/ics-dhcp/var
          type: Directory
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
