apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN ics-dhcp
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: ics-dhcp
    location: lan
  name: ics-dhcp
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/ics-dhcp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ics-dhcp
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN ics-dhcp
      creationTimestamp: null
      labels:
        k8s-app: ics-dhcp
        location: lan
      name: ics-dhcp
    spec:
      containers:
      - env:
        - name: tz
          value: UTC
        image: marvinmarvin/docker-k8s-ics-dhcp
        imagePullPolicy: Always
        name: ics-dhcp
        ports:
        - containerPort: 67
          name: dhcp
          protocol: UDP
        volumeMounts:
        - mountPath: /etc/dhcp
          name: k8s-cfg-ics-dhcp-etc
        - mountPath: /var/lib/dhcp
          name: k8s-cfg-ics-dhcp-var
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: k8s-cfg-ics-dhcp-etc
        hostPath:
          path: /root/k8s-cfg/ics-dhcp/etc
          type: Directory
      - name: k8s-cfg-ics-dhcp-var
        hostPath:
          path: /root/k8s-cfg/ics-dhcp/var
          type: Directory
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-esxi
    metallb.universe.tf/allow-shared-ip: lan-esxi
  labels:
    k8s-app: ics-dhcp
  name: ics-dhcp
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.250
  ports:
  - name: dhcp
    port: 67
    protocol: UDP
    targetPort: dhcp
  selector:
    k8s-app: ics-dhcp
  sessionAffinity: None
  type: LoadBalancer
